application: phparty7
version: 0-0-2
runtime: php55
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /data
  static_dir: data

- url: /elements
  static_dir: elements

- url: /bower_components
  static_dir: bower_components

- url: /
  script: index.html
